Name:           ros-lunar-rc-cloud-accumulator
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS rc_cloud_accumulator package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       pcl-devel
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-nav-msgs
Requires:       ros-lunar-pcl-ros
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-std-srvs
Requires:       ros-lunar-tf2
Requires:       ros-lunar-tf2-msgs
Requires:       ros-lunar-tf2-ros
BuildRequires:  pcl-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-nav-msgs
BuildRequires:  ros-lunar-pcl-ros
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-std-srvs
BuildRequires:  ros-lunar-tf2
BuildRequires:  ros-lunar-tf2-msgs
BuildRequires:  ros-lunar-tf2-ros

%description
A viewer for the SLAM component of roboception based on ROS and PCL

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Tue Jun 19 2018 Felix Endres <felix.endres@roboception.de> - 1.0.0-0
- Autogenerated by Bloom

